AWSTemplateFormatVersion: "2010-09-09"
Description: S3 bucket for Lambda deployment packages.

Resources:
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  LambdaCodeBucketName:
    Description: Name of the S3 bucket for Lambda code
    Value: !Ref LambdaCodeBucket
